### ISSUE TITLE
requirements.txt dependency confilct - old pandas version 0.22 is conflicting with osmnx 1.1.1

### ISSUE THREAD

**Issue by izzley** [mm80843/Places_Paris#1]
I'm using ubuntu20.04 running on windows10 WSL2 in vscode terminal.

There looks to be a conflict with pandas dependencies. Is there any reason pandas 0.22 version is requested in requirements.txt? If not, an easy fix could be as simple as upgrading pandas to latest version then re-freezing:

```bash
python -m pip install -U pandas
pip freeze > requirements.txt
```
I noticed the [latest pandas docs](https://pandas.pydata.org/docs/getting_started/install.html) request python 3.7+ but I suspect 3.6 will still work...

See below steps I took to get these errors:

1. setup virtual env with python3.10 and did `pip install -r requirements.txt` then got the following error message. My first thought was this was because I was using python version 3.10...

![20211123_2123_pandasversion](https://user-images.githubusercontent.com/72337941/143008119-b3f2a66c-3737-4754-abff-034706009ae2.png)

2. I setup a virtual env with python 3.6 and `pip install -r requirements.txt` but then I got a different error as shown below:

![20211123_2125_pandasdependency](https://user-images.githubusercontent.com/72337941/143008123-2940bec3-675f-4786-81b2-e1a7719a2bd2.PNG)

**Comment by mm80843** [comment]
Interesting, thanks for catching this. I'll try and update this. Definitely need to put up a pipenv in this folder.
Docker and PipEnv were used on the ["non-test" folders](https://github.com/mm80843/Places_Paris/tree/main/services) but did not apply this thinking to that one.

**Comment by mm80843** [comment]
As a sidenote, I used a [pipreq script](https://github.com/mm80843/Places_Paris/blob/main/utilities/createReqs.sh ) to create these reqs, but somehow Iit did not work properly..

**Comment by izzley** [comment]
No problems at all. If forgot to say I'm running Ubuntu20.04 on WSL2 (which should be same as Ubuntu20.04. I've add to the OP.

If you're happy on linux, I've never had issues with [pip freeze](https://pip.pypa.io/en/stable/cli/pip_freeze/) but they should be pretty much the same. 

So I tried changing the pip install requirements manually but ended up chasing my tail repeating the same steps for different packages:

![20211123_2215_deps](https://user-images.githubusercontent.com/72337941/143015105-ab1eccdc-73a9-4f68-b157-1d1c55de1230.png)
![20211123_2216_deps](https://user-images.githubusercontent.com/72337941/143015111-93fee408-96eb-4734-8596-21ad5134b818.png)
![20211123_2213_deps](https://user-images.githubusercontent.com/72337941/143015113-faaf43c0-4cd3-4259-bdd7-c37567bd34a4.png)

Looking at the original post last screenshot, I don't how to follow their suggestions: 
1. "_loosen" the range_" or 
2. " _remove package versions to allow pip attempt to solve the dependency conflict_".

**Comment by mm80843** [comment]
What about using pipenv ? 
As followin this config file :  https://github.com/mm80843/Places_Paris/blob/main/services/FastAPI/Pipfile

**Comment by izzley** [comment]
Oh great I'll give this a go tomorrow and let you know. Should I be using python 3.7?

**Comment by mm80843** [comment]
Indeed - normally should be specified in the pipfile =)

**Comment by izzley** [comment]
Sorry for the hiatus @mm80843. I'm not familiar with pipenv and have been short on time so ended up copying the versions from the pipfile and updating the `requirements.txt`. Definitely not the smartest way but it works ok for getting up and running with Python3.7:

```bash
pandas==1.3.4
Shapely==1.8.0
geopandas==0.10.2
geopy==2.2.0
pickle5==0.0.11
numpy==1.21.4
scipy==1.7.2
osmnx==1.1.1
streamlit==0.75.0
networkx==2.6.3
plotly==5.3.1
```
Thanks for your help on this 🤘

**Comment by mm80843** [comment]
Thanks to you! If that works on your side, happy to get your updated requirements.txt pushed ;)
